/* Generated by `supabase gen types typescript --project-id uvcivtqkdixosgulpwjd --schema public`. Do not edit; regenerate after migrations. */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      cleaning_teams: {
        Row: {
          created_at: string | null
          email: string | null
          home_lat: number | null
          home_lng: number | null
          id: string
          name: string
          phone: string | null
          quick_pay: boolean | null
          service_states: string[] | null
          subscription: string | null
        }
        Insert: {
          created_at?: string | null
          email?: string | null
          home_lat?: number | null
          home_lng?: number | null
          id?: string
          name: string
          phone?: string | null
          quick_pay?: boolean | null
          service_states?: string[] | null
          subscription?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string | null
          home_lat?: number | null
          home_lng?: number | null
          id?: string
          name?: string
          phone?: string | null
          quick_pay?: boolean | null
          service_states?: string[] | null
          subscription?: string | null
        }
        Relationships: []
      }
      contacts: {
        Row: {
          active: boolean | null
          created_at: string | null
          customer_id: string | null
          email: string | null
          full_name: string
          id: string
          phone: string | null
        }
        Insert: {
          active?: boolean | null
          created_at?: string | null
          customer_id?: string | null
          email?: string | null
          full_name: string
          id?: string
          phone?: string | null
        }
        Update: {
          active?: boolean | null
          created_at?: string | null
          customer_id?: string | null
          email?: string | null
          full_name?: string
          id?: string
          phone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contacts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string | null
          email_domain: string | null
          id: string
          name: string
        }
        Insert: {
          created_at?: string | null
          email_domain?: string | null
          id?: string
          name: string
        }
        Update: {
          created_at?: string | null
          email_domain?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      evidence: {
        Row: {
          id: number
          job_id: number | null
          kind: string
          lat: number | null
          lng: number | null
          taken_at: string | null
          url: string
        }
        Insert: {
          id?: number
          job_id?: number | null
          kind: string
          lat?: number | null
          lng?: number | null
          taken_at?: string | null
          url: string
        }
        Update: {
          id?: number
          job_id?: number | null
          kind?: string
          lat?: number | null
          lng?: number | null
          taken_at?: string | null
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs_unanswered"
            referencedColumns: ["job_id"]
          },
        ]
      }
      job_actions: {
        Row: {
          action: string
          at: string
          by_name: string | null
          id: number
          job_id: number | null
          payload: Json | null
          reason: string
        }
        Insert: {
          action: string
          at?: string
          by_name?: string | null
          id?: number
          job_id?: number | null
          payload?: Json | null
          reason: string
        }
        Update: {
          action?: string
          at?: string
          by_name?: string | null
          id?: number
          job_id?: number | null
          payload?: Json | null
          reason?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_actions_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_actions_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs_unanswered"
            referencedColumns: ["job_id"]
          },
        ]
      }
      job_addons: {
        Row: {
          addon: string
          at: string
          by_name: string | null
          cleaner_pay: number | null
          id: number
          job_id: number | null
          note: string | null
          price: number | null
        }
        Insert: {
          addon: string
          at?: string
          by_name?: string | null
          cleaner_pay?: number | null
          id?: number
          job_id?: number | null
          note?: string | null
          price?: number | null
        }
        Update: {
          addon?: string
          at?: string
          by_name?: string | null
          cleaner_pay?: number | null
          id?: number
          job_id?: number | null
          note?: string | null
          price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "job_addons_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_addons_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs_unanswered"
            referencedColumns: ["job_id"]
          },
        ]
      }
      job_events: {
        Row: {
          actor: string | null
          actor_type: string
          at: string
          detail: Json | null
          from_stage: Database["public"]["Enums"]["job_stage"] | null
          id: number
          job_id: number | null
          kind: string
          to_stage: Database["public"]["Enums"]["job_stage"] | null
        }
        Insert: {
          actor?: string | null
          actor_type: string
          at?: string
          detail?: Json | null
          from_stage?: Database["public"]["Enums"]["job_stage"] | null
          id?: number
          job_id?: number | null
          kind: string
          to_stage?: Database["public"]["Enums"]["job_stage"] | null
        }
        Update: {
          actor?: string | null
          actor_type?: string
          at?: string
          detail?: Json | null
          from_stage?: Database["public"]["Enums"]["job_stage"] | null
          id?: number
          job_id?: number | null
          kind?: string
          to_stage?: Database["public"]["Enums"]["job_stage"] | null
        }
        Relationships: [
          {
            foreignKeyName: "job_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs_unanswered"
            referencedColumns: ["job_id"]
          },
        ]
      }
      jobs: {
        Row: {
          access_notes: string | null
          ai_confidence: number | null
          assigned_at: string | null
          cancel_reason: string | null
          cancelled_at: string | null
          cleaner_pay: number | null
          contact_id: string | null
          created_at: string
          customer_id: string | null
          delayed: boolean | null
          evidence_pdf_sent: boolean | null
          field_sources: Json | null
          flagged: boolean | null
          id: number
          owner_id: string | null
          paid: boolean | null
          paid_at: string | null
          po_status: string | null
          price: number | null
          property_id: string | null
          quick_pay: boolean | null
          quickbooks_bill_id: string | null
          rating_customer: number | null
          rating_pinch: number | null
          request_body: string | null
          request_channel: string | null
          request_from: string | null
          request_name: string | null
          request_subject: string | null
          sender_confirmed: boolean | null
          sender_confirmed_by: string | null
          service: string | null
          stage: Database["public"]["Enums"]["job_stage"]
          stage_at: string
          team_asked_at: string | null
          team_confirmed: boolean | null
          team_id: string | null
          tracwork_id: string | null
          unit: string | null
          window_date: string | null
          window_end: string | null
          window_start: string | null
          workapp_id: string | null
          zendesk_ticket: string | null
        }
        Insert: {
          access_notes?: string | null
          ai_confidence?: number | null
          assigned_at?: string | null
          cancel_reason?: string | null
          cancelled_at?: string | null
          cleaner_pay?: number | null
          contact_id?: string | null
          created_at?: string
          customer_id?: string | null
          delayed?: boolean | null
          evidence_pdf_sent?: boolean | null
          field_sources?: Json | null
          flagged?: boolean | null
          id?: number
          owner_id?: string | null
          paid?: boolean | null
          paid_at?: string | null
          po_status?: string | null
          price?: number | null
          property_id?: string | null
          quick_pay?: boolean | null
          quickbooks_bill_id?: string | null
          rating_customer?: number | null
          rating_pinch?: number | null
          request_body?: string | null
          request_channel?: string | null
          request_from?: string | null
          request_name?: string | null
          request_subject?: string | null
          sender_confirmed?: boolean | null
          sender_confirmed_by?: string | null
          service?: string | null
          stage?: Database["public"]["Enums"]["job_stage"]
          stage_at?: string
          team_asked_at?: string | null
          team_confirmed?: boolean | null
          team_id?: string | null
          tracwork_id?: string | null
          unit?: string | null
          window_date?: string | null
          window_end?: string | null
          window_start?: string | null
          workapp_id?: string | null
          zendesk_ticket?: string | null
        }
        Update: {
          access_notes?: string | null
          ai_confidence?: number | null
          assigned_at?: string | null
          cancel_reason?: string | null
          cancelled_at?: string | null
          cleaner_pay?: number | null
          contact_id?: string | null
          created_at?: string
          customer_id?: string | null
          delayed?: boolean | null
          evidence_pdf_sent?: boolean | null
          field_sources?: Json | null
          flagged?: boolean | null
          id?: number
          owner_id?: string | null
          paid?: boolean | null
          paid_at?: string | null
          po_status?: string | null
          price?: number | null
          property_id?: string | null
          quick_pay?: boolean | null
          quickbooks_bill_id?: string | null
          rating_customer?: number | null
          rating_pinch?: number | null
          request_body?: string | null
          request_channel?: string | null
          request_from?: string | null
          request_name?: string | null
          request_subject?: string | null
          sender_confirmed?: boolean | null
          sender_confirmed_by?: string | null
          service?: string | null
          stage?: Database["public"]["Enums"]["job_stage"]
          stage_at?: string
          team_asked_at?: string | null
          team_confirmed?: boolean | null
          team_id?: string | null
          tracwork_id?: string | null
          unit?: string | null
          window_date?: string | null
          window_end?: string | null
          window_start?: string | null
          workapp_id?: string | null
          zendesk_ticket?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "jobs_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "operators"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "cleaning_teams"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          at: string
          body: string | null
          channel: string
          direction: string
          external_id: string | null
          from_addr: string | null
          from_name: string | null
          id: number
          job_id: number | null
          read_at: string | null
        }
        Insert: {
          at?: string
          body?: string | null
          channel: string
          direction: string
          external_id?: string | null
          from_addr?: string | null
          from_name?: string | null
          id?: number
          job_id?: number | null
          read_at?: string | null
        }
        Update: {
          at?: string
          body?: string | null
          channel?: string
          direction?: string
          external_id?: string | null
          from_addr?: string | null
          from_name?: string | null
          id?: number
          job_id?: number | null
          read_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs_unanswered"
            referencedColumns: ["job_id"]
          },
        ]
      }
      operators: {
        Row: {
          active: boolean | null
          email: string | null
          id: string
          name: string
          user_id: string | null
        }
        Insert: {
          active?: boolean | null
          email?: string | null
          id?: string
          name: string
          user_id?: string | null
        }
        Update: {
          active?: boolean | null
          email?: string | null
          id?: string
          name?: string
          user_id?: string | null
        }
        Relationships: []
      }
      properties: {
        Row: {
          address1: string | null
          address2: string | null
          city: string | null
          cleaners_count: number | null
          created_at: string | null
          customer_id: string | null
          default_team_id: string | null
          geocode_source: string | null
          geom: unknown
          id: string
          import_key: string | null
          lat: number | null
          lng: number | null
          manager_email: string | null
          manager_name: string | null
          manager_phone: string | null
          name: string
          origin: string | null
          postal_code: string | null
          registered_at: string | null
          state: string | null
          supervisor_email: string | null
          supervisor_name: string | null
          supervisor_phone: string | null
          type: string | null
          units_count: number | null
        }
        Insert: {
          address1?: string | null
          address2?: string | null
          city?: string | null
          cleaners_count?: number | null
          created_at?: string | null
          customer_id?: string | null
          default_team_id?: string | null
          geocode_source?: string | null
          geom?: unknown
          id?: string
          import_key?: string | null
          lat?: number | null
          lng?: number | null
          manager_email?: string | null
          manager_name?: string | null
          manager_phone?: string | null
          name: string
          origin?: string | null
          postal_code?: string | null
          registered_at?: string | null
          state?: string | null
          supervisor_email?: string | null
          supervisor_name?: string | null
          supervisor_phone?: string | null
          type?: string | null
          units_count?: number | null
        }
        Update: {
          address1?: string | null
          address2?: string | null
          city?: string | null
          cleaners_count?: number | null
          created_at?: string | null
          customer_id?: string | null
          default_team_id?: string | null
          geocode_source?: string | null
          geom?: unknown
          id?: string
          import_key?: string | null
          lat?: number | null
          lng?: number | null
          manager_email?: string | null
          manager_name?: string | null
          manager_phone?: string | null
          name?: string
          origin?: string | null
          postal_code?: string | null
          registered_at?: string | null
          state?: string | null
          supervisor_email?: string | null
          supervisor_name?: string | null
          supervisor_phone?: string | null
          type?: string | null
          units_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "properties_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "properties_team_fk"
            columns: ["default_team_id"]
            isOneToOne: false
            referencedRelation: "cleaning_teams"
            referencedColumns: ["id"]
          },
        ]
      }
      tracker: {
        Row: {
          arrive_lat: number | null
          arrive_lng: number | null
          arrived_at: string | null
          cleaner_notes: string | null
          ended_at: string | null
          job_id: number
          started_at: string | null
        }
        Insert: {
          arrive_lat?: number | null
          arrive_lng?: number | null
          arrived_at?: string | null
          cleaner_notes?: string | null
          ended_at?: string | null
          job_id: number
          started_at?: string | null
        }
        Update: {
          arrive_lat?: number | null
          arrive_lng?: number | null
          arrived_at?: string | null
          cleaner_notes?: string | null
          ended_at?: string | null
          job_id?: number
          started_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tracker_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tracker_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs_unanswered"
            referencedColumns: ["job_id"]
          },
        ]
      }
    }
    Views: {
      jobs_unanswered: {
        Row: {
          job_id: number | null
          unanswered: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      job_stage:
        | "pending"
        | "scheduled"
        | "in_progress"
        | "complete"
        | "validation"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      job_stage: [
        "pending",
        "scheduled",
        "in_progress",
        "complete",
        "validation",
      ],
    },
  },
} as const
